INSERT INTO PRODUCTO (NOMBRE ,PRECIO_UNITARIO) VALUES ('CERVEZA',180.00);
INSERT INTO PRODUCTO (NOMBRE ,PRECIO_UNITARIO) VALUES ('PAPAS FRITAS',200.00);
INSERT INTO PRODUCTO (NOMBRE ,PRECIO_UNITARIO) VALUES ('QUESO X KG',550.00);
INSERT INTO PRODUCTO (NOMBRE ,PRECIO_UNITARIO) VALUES ('SALAMIN',250.00);
INSERT INTO PRODUCTO (NOMBRE ,PRECIO_UNITARIO) VALUES ('JAMON COCIDO',150.00);
INSERT INTO PRODUCTO (NOMBRE ,PRECIO_UNITARIO) VALUES ('JAMON CRUDO',300.00);
INSERT INTO PRODUCTO (NOMBRE ,PRECIO_UNITARIO) VALUES ('GASEOSA',100.00);
INSERT INTO PRODUCTO (NOMBRE ,PRECIO_UNITARIO) VALUES ('VINO TINTO',700.00);
INSERT INTO PRODUCTO (NOMBRE ,PRECIO_UNITARIO) VALUES ('VINO BLANCO',600.00);
INSERT INTO PRODUCTO (NOMBRE ,PRECIO_UNITARIO) VALUES ('PAN',50.00);
INSERT INTO PRODUCTO (NOMBRE ,PRECIO_UNITARIO) VALUES ('ACEITUNAS',200.00);
INSERT INTO PRODUCTO (NOMBRE ,PRECIO_UNITARIO) VALUES ('HELADO X KG',900.00);
INSERT INTO PRODUCTO (NOMBRE ,PRECIO_UNITARIO) VALUES ('SALCHICAS',200.00);

INSERT INTO CLIENTE (DNI,NOMBRE ,ES_VIP) VALUES (29229726,'JUAN',1);
INSERT INTO CLIENTE (DNI,NOMBRE ,ES_VIP) VALUES (1111111,'PEDRO',0);
INSERT INTO CLIENTE (DNI,NOMBRE ,ES_VIP) VALUES (2222222,'ANA',0);
INSERT INTO CLIENTE (DNI,NOMBRE ,ES_VIP) VALUES (3333333,'LAURA',1);
INSERT INTO CLIENTE (DNI,NOMBRE ,ES_VIP) VALUES (4444444,'ALFONSO',0);
